<?php

namespace ContainerUxZlhlx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fdv0ar0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fdv0ar0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fdv0ar0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'atelier' => ['privates', '.errored..service_locator.Fdv0ar0.App\\Entity\\Ateliers', NULL, 'Cannot autowire service ".service_locator.Fdv0ar0": it references class "App\\Entity\\Ateliers" but no such service exists.'],
        ], [
            'atelier' => 'App\\Entity\\Ateliers',
        ]);
    }
}
