<?php

namespace ContainerTAAHxOW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAteliersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Fdv0ar0.App\Entity\Ateliers' shared service.
     *
     * @return \App\Entity\Ateliers
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Fdv0ar0": it references class "App\\Entity\\Ateliers" but no such service exists.');
    }
}
